### ISSUE TITLE
Scaffold CRD for SQLServerDatabase

### ISSUE THREAD

**Issue by josephaw1022** [DotKube/KubeSQLServer-Operator#1]
Implement the SQLServerDatabase Custom Resource Definition (CRD) to enable the declarative creation and management of individual databases within a SQL Server instance. This CRD will be part of the existing SQL Server operator and will enhance its functionality by allowing users to specify databases in a Kubernetes-native way.

Example Manifest

```
apiVersion: database.example.com/v1alpha1
kind: SQLServerDatabase
metadata:
  name: example-database
  namespace: sqlserver-example
spec:
  instanceName: sqlserver-instance
  databaseName: "exampleDB"
  collation: "SQL_Latin1_General_CP1_CI_AS"
  owner: "db_owner"
```
