### ISSUE TITLE
Add Users CRD to the operator

### ISSUE THREAD

**Issue by josephaw1022** [DotKube/KubeSQLServer-Operator#4]
come up with a sql server operator crd for db users

```
apiVersion: database.example.com/v1alpha1
kind: SQLServerUser
metadata:
  name: example-user
  namespace: sqlserver-example
spec:
  instanceName: sqlserver-instance
  username: "dbuser"
  passwordSecretName: "sqlserver-secret"
  roles:
    - db_owner
    - db_datareader
    - db_datawriter
  databases:
    - "exampleDB"
```

for the sake of getting this done, we will just stick to sql server username and password login method
